package com.jfinal.demo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_classify", "classifyId", Classify.class);
		arp.addMapping("sys_operatelog", "id", Operatelog.class);
		arp.addMapping("sys_picture", "picId", Picture.class);
		arp.addMapping("sys_user", "id", User.class);
	}
}

