package com.jfinal.demo.model;

import com.jfinal.demo.model.base.BaseClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify();
}
