package com.jfinal.demo.model;

import com.jfinal.demo.model.base.BaseOperatelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operatelog extends BaseOperatelog<Operatelog> {
	public static final Operatelog dao = new Operatelog();
}
