package com.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperatelog<M extends BaseOperatelog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOperateType(java.lang.String operateType) {
		set("operateType", operateType);
	}

	public java.lang.String getOperateType() {
		return get("operateType");
	}

	public void setOperateContent(java.lang.String operateContent) {
		set("operateContent", operateContent);
	}

	public java.lang.String getOperateContent() {
		return get("operateContent");
	}

	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}

	public java.util.Date getOperateTime() {
		return get("operateTime");
	}

	public void setOperateIP(java.lang.String operateIP) {
		set("operateIP", operateIP);
	}

	public java.lang.String getOperateIP() {
		return get("operateIP");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

}
