package com.jfinal.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassify<M extends BaseClassify<M>> extends Model<M> implements IBean {

	public void setClassifyId(java.lang.Integer classifyId) {
		set("classifyId", classifyId);
	}

	public java.lang.Integer getClassifyId() {
		return get("classifyId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setClassifyName(java.lang.String classifyName) {
		set("classifyName", classifyName);
	}

	public java.lang.String getClassifyName() {
		return get("classifyName");
	}

	public void setParentName(java.lang.String parentName) {
		set("parentName", parentName);
	}

	public java.lang.String getParentName() {
		return get("parentName");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
